### ISSUE TITLE
Node version doesnt support async function in manage_users script

### ISSUE THREAD

**Issue by tomrade** [hackmdio/docker-hackmd#36]
When I try and execute the manage_users script, I get a Node error about the line "async function"
A bit of googling shows this is function introduced in node 7.6 while the container is on an older version 6.13.0

```
/hackmd/bin/manage_users:23
async function createUser(argv) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)
```

Ive been experimenting with updating node to latest in the debian dockerfile, however ended up with some npm issues, so im going to trying updating both node and npm.

```
    # Install NPM dependencies and build project
    npm install n -g && \
    n stable && \
    npm install npm@latest -g && \
    npm install --global yarn && \
```

( I also updated Yarn as the version present had issues with proxies (1.3.2))

**Comment by tomrade** [comment]
Think the build issue I was having  was the NPM cache clean due to the newer version not supporting this without "force" changed it to verify as instructed by the error
```
npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead.
npm ERR!                                                                                                                                                                                                                                                                       
npm ERR! If you're sure you want to delete the entire cache, rerun this command with --force.                                                                                                                                                                                  

npm ERR! A complete log of this run can be found in:                                                                                                                                                                                                                           
npm ERR!     /root/.npm/_logs/2018-03-05T18_21_57_694Z-debug.log      
```
as below
```
    # Clean up this layer
    npm prune --production && \
    yarn cache clean && \
    #npm cache clean && \
    npm cache verify && \
```
