### ISSUE TITLE
config.json as a volume fails: illegal operation on a directory

### ISSUE THREAD

**Issue by mcnesium** [hackmdio/docker-hackmd#39]
Instead of environment variables I am trying to make `config.json` persistent by mounting a directory from the host into `/files` like this:

        volumes:
          - /etc/hackmd:/files

In the original working configuration, the environment variables were set like this:

        environment:
          - HMD_DB_URL=postgres://hackmd:*****@database:5432/hackmd
          - HMD_USECDN=false
          - HMD_DOMAIN=hackmd.domain.de
          - HMD_URL_ADDPORT=false
          - HMD_PROTOCOL_USESSL=true
          - HMD_ALLOW_FREEURL=true
          - HMD_IMAGE_UPLOAD_TYPE=filesystem

With the volume mounted into the container, the config file has this content:

    hackmd@4eb2e4442d8b:/hackmd$ cat config.json
    {
      "production": {
          "dburl": "postgres://hackmd:*****@database:5432/hackmd",
          "usecdn": false,
          "domain": "hackmd.domain.de",
          "urladdport": false,
          "usessl": true,
          "allowfreeurl": true,
          "imageUploadType": "filesystem"
      }
    }

To me this looks like the exact configuration. Still, the app will not come up correctly. The log claims an "illegal operation on a directory":

    $ docker logs hackmd_app_1
    2018/03/22 17:20:09 Waiting for host: hackmdPostgres:5432
    2018/03/22 17:20:09 Problem with dial: dial tcp 141.76.119.143:5432: getsockopt: connection refused. Sleeping 5s
    2018/03/22 17:20:14 Problem with dial: dial tcp 141.76.119.143:5432: getsockopt: connection refused. Sleeping 5s
    2018/03/22 17:20:19 Problem with dial: dial tcp 141.76.119.143:5432: getsockopt: connection refused. Sleeping 5s
    2018/03/22 17:20:24 Problem with dial: dial tcp 141.76.119.143:5432: getsockopt: connection refused. Sleeping 5s
    2018/03/22 17:20:29 Problem with dial: dial tcp 141.76.119.143:5432: getsockopt: connection refused. Sleeping 5s
    2018/03/22 17:20:34 Problem with dial: dial tcp 141.76.119.143:5432: getsockopt: connection refused. Sleeping 5s
    2018/03/22 17:20:39 Timeout after 30s waiting on dependencies to become available: [tcp://hackmdPostgres:5432]

    Sequelize [Node: 6.12.3, CLI: 2.8.0, ORM: 3.30.4]

    'db:migrate' errored after 8.79 ms
    Error: Error parsing url: undefined
        at Object.urlStringToConfigHash (/hackmd/node_modules/sequelize-cli/lib/helpers/config-helper.js:200:13)
        at Object.parseDbUrl (/hackmd/node_modules/sequelize-cli/lib/helpers/config-helper.js:205:22)
        at /hackmd/node_modules/sequelize-cli/lib/helpers/config-helper.js:21:24
        at tryCatcher (/hackmd/node_modules/bluebird/js/release/util.js:16:23)
        at Promise._settlePromiseFromHandler (/hackmd/node_modules/bluebird/js/release/promise.js:512:31)
        at Promise._settlePromise (/hackmd/node_modules/bluebird/js/release/promise.js:569:18)
        at Promise._settlePromiseCtx (/hackmd/node_modules/bluebird/js/release/promise.js:606:10)
        at Async._drainQueue (/hackmd/node_modules/bluebird/js/release/async.js:138:12)
        at Async._drainQueues (/hackmd/node_modules/bluebird/js/release/async.js:143:10)
        at Immediate.Async.drainQueues (/hackmd/node_modules/bluebird/js/release/async.js:17:14)
        at runCallback (timers.js:672:20)
        at tryOnImmediate (timers.js:645:5)
        at processImmediate [as _immediateCallback] (timers.js:617:5)
    2018-03-22T17:20:46.438Z - error: uncaughtException: EISDIR: illegal operation on a directory, read date=Thu Mar 22 2018 17:20:46 GMT+0000 (UTC), pid=33, uid=10000, gid=65534, cwd=/hackmd, execPath=/usr/local/bin/node, version=v6.12.3, argv=[/usr/local/bin/node, /hackmd/app.js], rss=91455488, heapTotal=75583488, heapUsed=44675696, external=41684, loadavg=[0.6572265625, 0.47314453125, 0.49072265625], uptime=686302, trace=[column=null, file=null, function=Error, line=null, method=null, native=true, column=19, file=fs.js, function=Object.fs.readSync, line=733, method=readSync, native=false, column=20, file=fs.js, function=tryReadSync, line=488, method=null, native=false, column=19, file=fs.js, function=Object.fs.readFileSync, line=536, method=readFileSync, native=false, column=13, file=/hackmd/app.js, function=null, line=58, method=null, native=false, column=32, file=module.js, function=Module._compile, line=570, method=_compile, native=false, column=10, file=module.js, function=Module._extensions..js, line=579, method=.js, native=false, column=32, file=module.js, function=Module.load, line=487, method=load, native=false, column=12, file=module.js, function=tryModuleLoad, line=446, method=null, native=false, column=3, file=module.js, function=Module._load, line=438, method=_load, native=false, column=10, file=module.js, function=Module.runMain, line=604, method=runMain, native=false, column=7, file=bootstrap_node.js, function=run, line=383, method=null, native=false, column=9, file=bootstrap_node.js, function=startup, line=149, method=null, native=false, column=3, file=bootstrap_node.js, function=null, line=496, method=null, native=false], stack=[Error: EISDIR: illegal operation on a directory, read,     at Error (native),     at Object.fs.readSync (fs.js:733:19),     at tryReadSync (fs.js:488:20),     at Object.fs.readFileSync (fs.js:536:19),     at Object.<anonymous> (/hackmd/app.js:58:13),     at Module._compile (module.js:570:32),     at Object.Module._extensions..js (module.js:579:10),     at Module.load (module.js:487:32),     at tryModuleLoad (module.js:446:12),     at Function.Module._load (module.js:438:3),     at Module.runMain (module.js:604:10),     at run (bootstrap_node.js:383:7),     at startup (bootstrap_node.js:149:9),     at bootstrap_node.js:496:3]

What's the matter here?

**Comment by SISheogorath** [comment]
Well, we use the `sequelize-cli` for database migrations. As HackMD is explicitly build to use environment variables for containerized setups, we do exactly this.

And the `.sequelizerc` is build to follow this rule:
https://github.com/hackmdio/docker-hackmd/blob/c7cdc9ec6f42845e28d66436215b7d19b406b88e/.sequelizerc#L7

Any reason why you want to use the config.json instead of environment variables?

**Comment by mcnesium** [comment]
Sorry for answering late.
> Any reason why you want to use the config.json instead of environment variables?
IMHO it is a bit messy to have the actual application configuration within `docker-compose.yml`, like the domain or what authentication methods this instance provides. It prevents this Docker configuration to be easily adapted on multiple instances.

If hackmd is explicitly build to use environment variables, then why is this configuration file there at all?

**Comment by SISheogorath** [comment]
@mcnesium the config file is for native setups. Means installed by hand and also updated by hand. This usually goes for development setup as well as some people who dislike docker.

For cloud/container setups like heroku and docker we adapt the [12factor app concept](https://12factor.net/). As we have static images build and bring in all config without relying on external files or similar.

If you want to replicate the config easily and have a separated file for configs, have a look at [docker-compose in production](https://docs.docker.com/compose/production/) from the Docker documentation. They explain in detail how to use multiple compose files to overwrite settings.

**Comment by mcnesium** [comment]
Ok looks like I am still not doing this Docker thing right. Thank you for pointing me to this :smile:
