### ISSUE TITLE
Warnings and errors during "docker-compose up" but does not prevent startup

### ISSUE THREAD

**Issue by philpraxis** [hackmdio/docker-hackmd#40]
```
app_1       | == 20171009121200-longtext-for-mysql: migrating =======
app_1       | >> WARNING: PostgreSQL does not support TEXT with options. Plain `TEXT` will be used instead. 
app_1       | >> Check: http://www.postgresql.org/docs/9.4/static/datatype.html
database_1  | ERROR:  column "latContent" of relation "Revisions" does not exist
database_1  | STATEMENT:  ALTER TABLE "Revisions" ALTER COLUMN "latContent" DROP NOT NULL;ALTER TABLE "Revisions" ALTER COLUMN "latContent" DROP DEFAULT;ALTER TABLE "Revisions" ALTER COLUMN "latContent" TYPE TEXT;
app_1       | Unhandled rejection SequelizeDatabaseError: column "latContent" of relation "Revisions" does not exist
app_1       |     at Query.formatError (/hackmd/node_modules/sequelize/lib/dialects/postgres/query.js:357:14)
app_1       |     at Result.<anonymous> (/hackmd/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
app_1       |     at emitOne (events.js:96:13)
app_1       |     at Result.emit (events.js:188:7)
app_1       |     at Result.Query.handleError (/hackmd/node_modules/pg/lib/query.js:163:8)
app_1       |     at Client.<anonymous> (/hackmd/node_modules/pg/lib/client.js:188:26)
app_1       |     at emitOne (events.js:96:13)
app_1       |     at Connection.emit (events.js:188:7)
app_1       |     at Socket.<anonymous> (/hackmd/node_modules/pg/lib/connection.js:133:12)
app_1       |     at emitOne (events.js:96:13)
app_1       |     at Socket.emit (events.js:188:7)
app_1       |     at readableAddChunk (_stream_readable.js:176:18)
app_1       |     at Socket.Readable.push (_stream_readable.js:134:10)
app_1       |     at TCP.onread (net.js:559:20)
app_1       | == 20171009121200-longtext-for-mysql: migrated (0.054s)
app_1       | (node:33) DeprecationWarning: Using the automatically created return value from client.query as an event emitter is deprecated and will be removed in pg@7.0. Please see the upgrade guide at https://node-postgres.com/guides/upgrading
app_1       | >> WARNING: PostgreSQL does not support TEXT with options. Plain `TEXT` will be used instead. 
app_1       | >> Check: http://www.postgresql.org/docs/9.4/static/datatype.html
app_1       | 2018-03-24T11:10:30.957Z - info: HTTP Server listening at port 3000
```

**Comment by SISheogorath** [comment]
yes, this migration error was fixed in master.

I'm not sure if we should break on a migration error. they sometimes appear without a good reason for example when something already has the desired state but didn't run the migration. (which can also mean our migration code is broken) So I'm not sure if we really want to prevent the container start as it maybe results in a completely broken situation.
